name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: browniebroke/pre-commit-autoupdate-action@main
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "🛠️ Update `pre-commit` hooks version"
          body: Update the `pre-commit` hooks to the latest versions.
